height: 256
weight: 256
optim: adamw
lr: 0.0003
weight_decay: 0.05
max_epoch: 60
train_batch_size: 32
test_batch_size: 32
stepsize: [20, 30]
gamma: 0.1
warmup_iters: 5
warmup_factor: 0.01
warmup_method: linear
arch: vip_small
root: /home/xyc/datasets/
datasetname: vessel_min
